name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the branch
              uses: actions/checkout@v4
            - name: Welcome message
              run: | 
                echo "My first app"
                ls -lrt
                cat README.md
            - name: Generate ASCII
              run: cowsay -f dragon "Run for cover, I am a dragon" >> dragon.txt