name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "My first app"
            - name: List files
              run: ls
            - name: Read my files
              run: cat ../README.md