name: Generate ASCII

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the branch
              uses: actions/checkout@v4
            - name: install cowsay app
              run: sudo apt-get install cowsay -y
            - name: Generate ASCII
              run: cowsay -f dragon "Run for cover, I am a dragon" >> dragon.txt

            