name: Generate ASCII

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the branch
              uses: actions/checkout@v4
            - name: install cowsay app using shell script
              run: | 
                chmod +x ascii-script.sh
                ./ascii-script.sh

            