name: Exploring Variables and Secrets

on:
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: docker build -t docker.io/dockerUsername/imageName:latest
            - name: Docker Login
              run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            - name: Docker Publish
              run: docker push docker/io/dockerUsername/imageName:latest
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest